apiVersion: v1
kind: Service
metadata:
  name: azure-aks-lab
  labels:
    app: azure-aks-lab
spec:
  type: ClusterIP
  selector:
    app: azure-aks-lab
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80